[tox]
envlist = format, lint, type, test
isolated_build = true

[testenv]
extras = dev

[testenv:format]
commands = black --check src tests utils

[testenv:lint]
extras = dev,utils
commands =
    flake8 --config=.flake8 src tests utils
    pylint src/simple_ticketing tests utils

[testenv:type]
extras = dev,utils
commands = mypy src/simple_ticketing utils

[testenv:test]
commands = pytest -v --tb=short
